name: Print Github Error and Notice features
on:
  pull_request:
jobs: 
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Error
      run: |
        var="Pozdro Synek"
        print \
          "::error" \
          " title=Incorrect Metadata Component Assignment" \
          ",file=" $var \
          "::Standard Value Set, Duplicate rule or Matching rule incorrectly located in a package dir."
