name: Print Github Error and Notice features
on:
  pull_request:
    branches:
      - main
jobs: 
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Error v3
        shell: bash
        run: |
          fileYml=print-error-notice.ymlW
          echo \
            "::error" \
            "title=Sample title" \
            ",file=$fileYml" \
            "::MS/G. '$fileYml'"
