name: Print Github Error and Notice features
on:
  pull_request:
    branches:
      - main
jobs: 
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Error v3
        shell: bash
        run: |
          echo "::error \
          title=Sample title \
          file=.github/workflows/print-error-notice.yml \
          ::MSG."
