name: Print Github Error and Notice features
on:
  pull_request:
    branches:
      - main
jobs: 
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Error based on docu
        run: echo "::error file=.github/workflows/print-error-notice.yml,line=1::Missing semicolon"
      - name: Print Error v1
        shell: bash
        run: | 
          print "::error title=Sample title,file=.github/workflows/print-error-notice.yml::MSG."
      - name: Print Error v2
        shell: bash
        run: |
          print \
            "::error" \
            " title=Sample title" \
            ",file=.github/workflows/print-error-notice.yml" \
            "::MSG."
